package utilities;

public enum BPMNElementTagName {
task,
sequenceFlow,
parallelGateway,
exclusiveGateway,
complexGateway,
eventBasedGateway,
dataStoreReference,
collaboration,
participant,
process,
definitions,
ioSpecification,
dataOutput,
inputSet,
outputSet,
dataOutputRefs,
dataInput,
dataInputRefs,
dataStore,
conditionExpression,
subProcess,
startEvent,
endEvent,
dataOutputAssociation,
dataInputAssociation,
association,
textAnnotation,
text,
multiInstanceLoopCharacteristics
}
